### ISSUE TITLE
サービス関連の画面を用意する

### ISSUE THREAD

**Issue by YukaChoco** [ikkei1616/watnowseikabutusite#1]
サービス関連必要なページ分の画面を用意する。
URLは[https://www.notion.so/fb4f2a423f934f7a98a93f91ad00dfac](Notion)を参照。
PRの作り方は森岡のPRを参照。

**Comment by ikkei1616** [comment]
ページを作成する際は、そのページがなんのページであるかをページ内に明記(ex.サービス一覧、サービス詳細など)
